INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (1,'Mercury','Mercury.JPG','200,900,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (2,'Venus','Venus.JPG','300,800,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (3,'Earth','Earth.JPG','400,700,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (4,'Mars','Mars.JPG','200,900,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (5,'Jupiter','Jupiter.JPG','300,800,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (6,'Saturn','Saturn.JPG','400,700,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (7,'Uranus','Uranus.JPG','200,900,000');
INSERT INTO PLANET_DETAILS (PLANET_ID,PLANET_NAME,IMAGE,DISTANCE) VALUES (8,'Neptune','Neptune.JPG','300,800,000');


